### ISSUE TITLE
Prenotazione

### ISSUE THREAD

**Issue by AlessandroTigani** [Project-SWEnergy/Easy-Meal#14]
- La prenotazione inviata con successo non produce nessun effetto, dovrebbe reindirizzare ad una pagina differente, un riepilogo, qualcosa.
- Effettuando una prenotazione alle 20, nel database la data salvata diventa 22: bisogna rimuovere il timezone offset dall'orario nella creazione di una prenotazione

**Comment by alvide** [comment]
Ora la prenotazione inviata con successo rinvia alla lista delle prenotazioni. Le due ore che venivano aggiunte alla prenotazione sono state risolte
