### ISSUE TITLE
La pagina di registrazione deve avere un link alla registrazione come ristoratore

### ISSUE THREAD

**Issue by AlessandroTigani** [Project-SWEnergy/Easy-Meal#7]
Diventa un problema non averla nel momento in cui la home non è più quella con login / registrazione.
- #4

**Comment by rossoc** [comment]
Non sono d'accrdo, i ristoranti si registrano molto poco spesso, piuttosto la pagina dove ci sono tutti i bottoni di registrazioni e login dovrebbe essere divisa in due: una diventa `about us` e l'altra `autenticazione`. Dal momento che in un'applicazione di questo tipo ci sono molti più utenti base piuttosto che ristoranti, mi sembra decisamente scorretto inserire il riferimento alla pagina di registrazione dei ristoranti all'interno della registrazione del cliente
