### ISSUE TITLE
Notifiche

### ISSUE THREAD

**Issue by AlessandroTigani** [Project-SWEnergy/Easy-Meal#9]
Il controllo delle notifiche avviene anche se l'utente non è loggato, il che si traduce in una notifica di errore (utente non autorizzato) ogni secondo.

**Comment by rossoc** [comment]
Questo avviene solo se l'utente era autenticato e quindi se nel localStorage del sito sono presenti i dati delle credenziali, ma i cookie non sono validi. Provvedo a correggere
